name: C++ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows because you have app.exe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
        choco install visualstudio2019buildtools -y
        choco install git -y

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run main executable
      run: build\Release\app.exe

    - name: Run tests using CTest
      run: cmake --build build --config Release && cd build && ctest --output-on-failure -C Release

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-executable
        path: build\Release\app.exe
