name: C++ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ build-essential

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run main executable
      run: ./build/app

    - name: Run tests
      run: |
        if [ -f build/tests/runTests ]; then
          ./build/tests/runTests
        else
          echo "No tests found"
        fi

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-executable
        path: build/app
